### ISSUE TITLE
[1.16.5] Datapack world loading issue

### ISSUE THREAD

**Issue by TheSnowyChickens** [gisellevonbingen/Minecraft-MoreMekanismProcessing#11]
Hello again :D

I removed your mod for testing something with my modpack aaaaaand then I could not load my world anymore.
Something with datapacks are blocking my world.
(I know this type of bug, "Titanium" (the lib mod from Industrial Foregoing) had the same problem with disabling their gears in the config, but at some point they released a update to fix this - maybe you can ask them what they did, if you want to fix it very fast)

![grafik](https://user-images.githubusercontent.com/29357962/129270353-38e33ac4-a633-48bf-b05b-710c75a7fc95.png)
Ps: the "safe mode" button is hard useless -> it just don't work

Forge: 36.2.2
MC: 1.16.5
MMOP: 0.5
Meka: .448

**Comment by gisellevonbingen** [comment]
It seems to be a data tag related problem.
Can you upload the log file at the time?

**Comment by gisellevonbingen** [comment]
Try bellow

1. Download NBT Explorer [[Link]](https://github.com/jaquadro/NBTExplorer/releases)
2. Open level.dat in that world directory
3. Delete fml tag
4. Save and join world again

![image](https://user-images.githubusercontent.com/44163945/129286140-a1066f63-2758-469f-879a-988448a2226a.png)

**Comment by gisellevonbingen** [comment]
I found exact cause.
It's related mekanism slurry registration

For solve his problem,
Dirty, Clean Slurries will register again as other name

**Comment by gisellevonbingen** [comment]
607f03be32883f2648e3f5dfbfa1f731f91f047d
not tested yet

**Comment by TheSnowyChickens** [comment]
Hi,
I can test all the stuff and give you datas in ~6 hours.
(I need some sleep xd)
During the night, I had my gmx not open, sry.

**Comment by gisellevonbingen** [comment]
take it slow
next version 1.16.5-0.6 was released
could you test that version later?

**Comment by TheSnowyChickens** [comment]
Okay, here we go:

log with the loading fail:
- [2021-08-13-1.log](https://github.com/gisellevonbingen/Minecraft-MoreMekanismProcessing/files/6984127/2021-08-13-1.log)

World loading with -0.6:
- ohhhmmmmmm
![grafik](https://user-images.githubusercontent.com/29357962/129395705-cd068cf3-2a5e-4180-a6d3-ce937c43d678.png)

I try the nbt explorer version and then I will update this post.

**Comment by gisellevonbingen** [comment]
That's good
Applaud your efforts 👏
