### ISSUE TITLE
Subterra

### ISSUE THREAD

**Issue by Afrocntrik** [gisellevonbingen/Minecraft-MoreMekanismProcessing#19]
This mod is newer but has a lot of possibilities for compatibility https://www.curseforge.com/minecraft/mc-mods/subterra

**Comment by Afrocntrik** [comment]
And if you do thank you, your mod is great

**Comment by gisellevonbingen** [comment]
I'm take a look data folder in mod jar file
Is that mod doesn't has forge:ores/XXX blocks?
I can't found tagged blocks

**Comment by gisellevonbingen** [comment]
* Google translate

Subterra is under development, so there is a possibility that the developer will add tags.
Could you make a suggestion to the Subterra developers first?
If the developer answers 'NO', I'll write the compliant code

**Comment by gisellevonbingen** [comment]
Subterra developer seems very busy, no reply
Instead I will write compatible code
Maybe apply to v0.10?

**Comment by gisellevonbingen** [comment]
Investigated Subterra items.
Almost all of the ore does not processing ore to ingot directly
There are many combinations of Subterra unique, so it seems inappropriate to apply it to this mode.

Perhaps it would be better to split it into separate modes.
Like 'Subtera Addon (Mechanism Processing)'

So sorry
