### ISSUE TITLE
Config changes

### ISSUE THREAD

**Issue by benbenlaw** [gisellevonbingen/Minecraft-MoreMekanismProcessing#23]
i have disabled certain ores in the config file without the game being loaded.
loading into the game the config works correctly then seemingly at random the config changes and a second config appears 
![image](https://user-images.githubusercontent.com/42780877/133972574-373df928-184e-4c8c-96ac-065f53107459.png)
i know this sometimes happens when the configs are changed whilst the game is running however this is happening without any changes to the file whilst the game is open

**Comment by gisellevonbingen** [comment]
i can't reproduce that situation
what you use version of mod?

**Comment by benbenlaw** [comment]
1.1, it seems to happen randomly sometimes after doing /reload

**Comment by gisellevonbingen** [comment]
it's still
can you tell you installed mod list?

**Comment by benbenlaw** [comment]
70 ish mods 
/reload comes from kubejs

**Comment by gisellevonbingen** [comment]
ok i will test with kubejs

**Comment by gisellevonbingen** [comment]
it's still, i tried possible every reload
but bak file not created

**Comment by benbenlaw** [comment]
yeah

**Comment by benbenlaw** [comment]
i will try to keep an eye on the file as i work on my modpack a see if i notice whats casuing it

**Comment by gisellevonbingen** [comment]
thx for your effort
if any issue occurred, please tell me

**Comment by benbenlaw** [comment]
it appears to be on start up that it changes

![image](https://user-images.githubusercontent.com/42780877/133989563-c3116cda-c98b-4bd0-b5f1-64988acfbc52.png)
its creating a new config file for some reason

**Comment by gisellevonbingen** [comment]
then.. can you upload your config toml file?

**Comment by benbenlaw** [comment]
[general]
	#true : show all recipes
	#false : hide ore not exist recipes (can hide recipes when some mod not installed)
	showOreNotExistRecipes = false

#processingLevel : set ores processing max level
#    5 : can into up x5 (able all procssing)
#    4 : can into up x4 (disable ore dissolution, slurry crystalizing)
#    3 : can into up x3 (disable injecting)
#    2 : can into up x2 (disable purifying and clumps crushing)
#    1 : reserved (currently same with 0)
#    0 : disable all processing in this mod
#disabled processing items are removed your world
[ores]

	[ores.electrotine]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.crimson_iron]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.titanium]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.green_sapphire]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.cobalt]
		#Range: 0 ~ 5
		processingLevel = 5

	[ores.aluminum]
		#Range: 0 ~ 5
		processingLevel = 5

	[ores.amethyst]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.cinnabar]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.apatite]
		#Range: 0 ~ 5
		processingLevel = 5

	[ores.iridium]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.lithium]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.platinum]
		#Range: 0 ~ 5
		processingLevel = 5

	[ores.tungsten]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.peridot]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.sulfur]
		#Range: 0 ~ 5
		processingLevel = 5

	[ores.lapis]
		#exist for modpacks, set greater than 2 to enable this material recipes
		#less than or equals 2 is use Mekanism Default Recipes
		#    warning : when enabled, ore block can infinitely regenerate using Mekanism Combiner Default Recipe
		#    propose remove/override Mekanism Combiner Default Recipe
		#    e.g.) "ingredient":{"tag":"forge:dusts/lapis"}},"amount":8
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.zinc]
		#Range: 0 ~ 5
		processingLevel = 5

	[ores.sapphire]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.bort]
		#Range: 0 ~ 5
		processingLevel = 5

	[ores.nickel]
		#Range: 0 ~ 5
		processingLevel = 5

	[ores.azure_silver]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.quartz]
		#exist for modpacks, set greater than 2 to enable this material recipes
		#less than or equals 2 is use Mekanism Default Recipes
		#    warning : when enabled, ore block can infinitely regenerate using Mekanism Combiner Default Recipe
		#    propose remove/override Mekanism Combiner Default Recipe
		#    e.g.) "ingredient":{"tag":"forge:dusts/quartz"}},"amount":8
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.draconium]
		#Range: 0 ~ 5
		processingLevel = 5

	[ores.ruby]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.diamond]
		#exist for modpacks, set greater than 2 to enable this material recipes
		#less than or equals 2 is use Mekanism Default Recipes
		#    warning : when enabled, ore block can infinitely regenerate using Mekanism Combiner Default Recipe
		#    propose remove/override Mekanism Combiner Default Recipe
		#    e.g.) "ingredient":{"tag":"forge:dusts/diamond"}},"amount":8
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.dilithium]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.silicon]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.desh]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.niter]
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.coal]
		#exist for modpacks, set greater than 2 to enable this material recipes
		#less than or equals 2 is use Mekanism Default Recipes
		#    warning : when enabled, ore block can infinitely regenerate using Mekanism Combiner Default Recipe
		#    propose remove/override Mekanism Combiner Default Recipe
		#    e.g.) "ingredient":{"tag":"forge:dusts/coal"}},"amount":8
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.silver]
		#Range: 0 ~ 5
		processingLevel = 5

	[ores.redstone]
		#exist for modpacks, set greater than 2 to enable this material recipes
		#less than or equals 2 is use Mekanism Default Recipes
		#    warning : when enabled, ore block can infinitely regenerate using Mekanism Combiner Default Recipe
		#    propose remove/override Mekanism Combiner Default Recipe
		#    e.g.) "ingredient":{"tag":"forge:dusts/redstone"}},"amount":8
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.emerald]
		#exist for modpacks, set greater than 2 to enable this material recipes
		#less than or equals 2 is use Mekanism Default Recipes
		#    warning : when enabled, ore block can infinitely regenerate using Mekanism Combiner Default Recipe
		#    propose remove/override Mekanism Combiner Default Recipe
		#    e.g.) "ingredient":{"tag":"forge:dusts/emerald"}},"amount":8
		#Range: 0 ~ 5
		processingLevel = 0

	[ores.bismuth]
		#Range: 0 ~ 5
		processingLevel = 0

**Comment by benbenlaw** [comment]
36.2.4

**Comment by gisellevonbingen** [comment]
sadly, still can't reproduce with your uploaded file too
has you any plugin in notepad++ what autosave when file changed?

**Comment by benbenlaw** [comment]
the files are closed when this is happening

**Comment by gisellevonbingen** [comment]
so weird
i had change line ending, encoding, etc.
but back file not created

I'm sorry I can't fix it right now

**Comment by benbenlaw** [comment]
thats ok

**Comment by Gbergz** [comment]
Old issue, yes. But I keep having this issue aswell. On 1.18.2 latest release.
Every time I start the server this happens:

`[net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file /home/mch/multicraft/servers/server66685/config/moremekanismprocessing-common.toml is not correct. Correcting` 

aand config gets reset and nobody can join because of it.

**Comment by Gbergz** [comment]
Update:
The config gets reset each time server boots, leading to stuff I've disabled to be enabled meaning no one can join because of the unregistered items, which are disabled on the client. 

Tried uploading the common-config from the client multiple times and it only works 1 time out of like 10 times.
The other 9 times a .bak file of the config gets created, meaning the config got corrupt? or something.
`[net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file server66685/config/moremekanismprocessing-common.toml is not correct. Correcting` 

And editing that newly generated config to the values I need corrupts/resets it aswell..

**Comment by Gbergz** [comment]
Update 2: 
@For now I've restored the config to it's normal state with no changes at all and disabled all other items not in use with KubeJS instead, since config keeps corrupting/resetting itself. Works for now.

**Comment by gisellevonbingen** [comment]
> Update 2: For now I've restored the config to it's normal state with no changes at all and disabled all other items not in use with KubeJS instead, since config keeps corrupting/resetting itself. Works for now.

Sorry i saw late
Can you upload your modified moremekanismprocessing-common.toml file?

Synchronization of config between client and server is not yet supported.
Copy the same config file as the server to the client

**Comment by Gbergz** [comment]
I will upload it in a bit.
I did upload from client to server and viceversa.
Still "corrupts/resets" the config.
