### ISSUE TITLE
Server Crashing 

### ISSUE THREAD

**Issue by DevEvelynn** [gisellevonbingen/Minecraft-MoreMekanismProcessing#24]
Idk why but whenever i try load it up it keeps crashing
https://mclo.gs/GnNv0SC

**Comment by gisellevonbingen** [comment]
i guess invalid value in 'moremekanismprocessing-common.toml'
example not a number

**Comment by gisellevonbingen** [comment]
can u upload that file?

**Comment by DevEvelynn** [comment]
[moremekanismprocessing-common.zip](https://github.com/gisellevonbingen/Minecraft-MoreMekanismProcessing/files/7216512/moremekanismprocessing-common.zip)

**Comment by DevEvelynn** [comment]
wouldn't let me upload it as a .toml

**Comment by gisellevonbingen** [comment]
this file is crashed
all bytes are \0

try delete this file

![image](https://user-images.githubusercontent.com/44163945/134486935-371fc199-afff-4245-8c73-68968bb826d8.png)

**Comment by DevEvelynn** [comment]
oki

**Comment by DevEvelynn** [comment]
https://mclo.gs/p70Yfr9

**Comment by DevEvelynn** [comment]
now its throwing another issue w/ a different mod

**Comment by gisellevonbingen** [comment]
is that all of log?
i guess 'Traverse: Reforged', 'Cuneiform ' mod's config file also crached

**Comment by DevEvelynn** [comment]
yeah it seems so thanks

**Comment by gisellevonbingen** [comment]
ok, i will add new issue what handle for config error instead crash
thanks for your attention this mod

**Comment by DevEvelynn** [comment]
it seems most of my config files have become corrupt
