### ISSUE TITLE
CRASH with the new Mekanism 10.1

### ISSUE THREAD

**Issue by Cynix32** [gisellevonbingen/Minecraft-MoreMekanismProcessing#25]
More Mekanism processing crashes at startup (fail to initialize class) with the newest release of mekanism 10.1
CRASHLOG: https://pastebin.com/DAsJACcm
Mekanism Addons also has this issue, I assume a lot of changes both on user side and internal code side were implemented with the new mekanism.

**Comment by gisellevonbingen** [comment]
An issue with Mekanism Addon affected MoreMekanismProcessing
1. 'Mekanism Addon' try inject mixin code to 'Mekanism'
2. That mixin code is crashed on 'Mekansim' 10.1
3. As a result, 'Mekanism' s class load failed
4. by the way, 'MoreMekanismProcessing' try access to failed class
5. Finally 'MMP' is crash too

If you uninstall Mekanism Addon, the problem should not occur.
