### ISSUE TITLE
[Request] Voluminous Energy support

### ISSUE THREAD

**Issue by Lurmey** [gisellevonbingen/Minecraft-MoreMekanismProcessing#29]
Voluminous Energy adds lots of mineral ores like Galena and Rutile that would be great to process with Mekanism.

https://www.curseforge.com/minecraft/mc-mods/voluminous-energy

**Comment by gisellevonbingen** [comment]
Ok I will check

**Comment by gisellevonbingen** [comment]
But rutile ore is support already as Titanium

**Comment by Lurmey** [comment]
Thanks very much. Processing rutile into titanium is what I'd like to see, on 1.16.5, please!

**Comment by gisellevonbingen** [comment]
Ok then, I will work 1.16, 1.18 both

**Comment by gisellevonbingen** [comment]
It Done
can download at here https://www.curseforge.com/minecraft/mc-mods/more-mekanism-processing/files/3776084
