### ISSUE TITLE
config doesnt hide items/fluids

### ISSUE THREAD

**Issue by ZEROX7** [gisellevonbingen/Minecraft-MoreMekanismProcessing#32]
hey so in the config/moremekanismprocessing-common.toml
there is a option to hide not ues items like for example iriduim if non ores are present it doesnt work
and also why is a client-1.toml.bak created each start?
![image](https://user-images.githubusercontent.com/12628051/166126146-84870b31-ab51-44c4-826a-7ce740f68de2.png)
![image](https://user-images.githubusercontent.com/12628051/166126156-916793c3-1d4d-40e4-bc6e-4605b2b7bf27.png)
![image](https://user-images.githubusercontent.com/12628051/166126163-692230f9-a38e-401c-afdd-d7120f53057f.png)

**Comment by gisellevonbingen** [comment]
Hide only recipes in JEI
If you hide unused items, set processing level in config file (moremekanismprocessing-common.toml)

Config file creating is fixing
Can you try after new version updated?

**Comment by ZEROX7** [comment]
updated to 2.2 even disabled the processing for all of them except cobalt and zinc but there still all listed
![image](https://user-images.githubusercontent.com/12628051/166153679-fbcb2782-e8bd-4043-b9c5-49a3bb06f692.png)
![image](https://user-images.githubusercontent.com/12628051/166153704-0f9bc5b6-a27f-44a2-895d-501eb74f1016.png)

**Comment by ZEROX7** [comment]
it even displays more items than before

**Comment by gisellevonbingen** [comment]
ah, ok
i will find solution

**Comment by gisellevonbingen** [comment]
Fixed at version 1.18.2-2.4 (https://www.curseforge.com/minecraft/mc-mods/more-mekanism-processing/files/3776980)
![image](https://user-images.githubusercontent.com/44163945/166180031-494d951f-0fc4-4e7b-85a9-2fd4d2839c0b.png)
![image](https://user-images.githubusercontent.com/44163945/166180083-9afaade1-1b5a-4c1f-9636-6af3bd9dfb0b.png)

**Comment by gisellevonbingen** [comment]
Is problem solved?

**Comment by ZEROX7** [comment]
yes sry that i didnt answer

**Comment by SiriosDev** [comment]
I'm sorry to re-give activity to this issue, but, in the JEI the slurries are all visible despite the config, whereas in the emi it is all visible
