### ISSUE TITLE
Compatibility of Bismuth with Enlightened End's Bismuth?

### ISSUE THREAD

**Issue by ratemisia** [gisellevonbingen/Minecraft-MoreMekanismProcessing#42]
Enlightened End at https://www.curseforge.com/minecraft/mc-mods/enlightend adds a Bismuth ore to the End, which doesn't seem to be recognized by this mod when I've tested it. Otherwise, it could use the preexisting Bismuth processing in this mod.

**Comment by gisellevonbingen** [comment]
That is Enlightened's problem.
The mod does not use tag for any recipes and items.
![image](https://github.com/gisellevonbingen-Minecraft/MoreMekanismProcessing/assets/44163945/01230935-9db5-4f7f-9983-453fed15e7c9)

In example, 'Bismuth Ingot' should have 'forge:ingots/bismuth' tag like this.
![image](https://github.com/gisellevonbingen-Minecraft/MoreMekanismProcessing/assets/44163945/fbc3738a-5919-4a15-9108-46c1cba49237)

Below is recipe json for craft 'Bismuth Block' from 'Bismusth Ingot'. (other recipes same)
```json
{
  "type": "minecraft:crafting_shaped",
  "group": "bismuth_block",
  "category": "building",
  "pattern": [
    "012",
    "345",
    "678"
  ],
  "key": {
    "0": {
      "item": "enlightened_end:bismuth_ingot"
    },
    "1": {
      "item": "enlightened_end:bismuth_ingot"
    },
    "2": {
      "item": "enlightened_end:bismuth_ingot"
    },
    "3": {
      "item": "enlightened_end:bismuth_ingot"
    },
    "4": {
      "item": "enlightened_end:bismuth_ingot"
    },
    "5": {
      "item": "enlightened_end:bismuth_ingot"
    },
    "6": {
      "item": "enlightened_end:bismuth_ingot"
    },
    "7": {
      "item": "enlightened_end:bismuth_ingot"
    },
    "8": {
      "item": "enlightened_end:bismuth_ingot"
    }
  },
  "result": {
    "item": "enlightened_end:bismuth_block",
    "count": 1
  }
}
```

That recipe is declare only ingredient as 'item'.
Then there is no possibility for other modes to intervene.

In basically, need to use tag for be compatibility.
 `"item": "enlightened_end:bismuth_ingot"` should change be `"tag": "forge:ingots/bismuth"` or similar.


This mod will have compatibility automatically when Enlightened give tag to items and use tag at recipe json.

**Comment by ratemisia** [comment]
Thanks for the reply!
So, if I were to use a tool locally like KubeJS to change Enlightend's recipes and items to use Forge tags, would this allow compatibility? This might help me allow other mods' compatibility with this addon as well.

**Comment by gisellevonbingen** [comment]
Yes, indeed.
These two tags are important
|Item|Tag should having|
|-|-|
|Bismuth Ore|forge:ores/bismuth|
|Bismuth Ingot|forge:ingots/bismuth|

**Comment by ratemisia** [comment]
Very helpful, this will solve my issue with compatibility. Thank you!
