### ISSUE TITLE
[Forge 1.20.1] Ingot should auto-disable themselves if another mod adds them

### ISSUE THREAD

**Issue by vizthex123** [gisellevonbingen/Minecraft-MoreMekanismProcessing#44]
Bit annoying to have multiple of the same ingot.

Alternatively, adding a whitelist in the config that lets us specify mod favour order would be nice (like Tinker's Construct did - by default, it would make TConstruct ingots before looking for ones from other mods).

**Comment by gisellevonbingen** [comment]
Sorry for late reply.
Due to the way this mod works, even if there is no mod, at least one ingot is required,
So one ingot was added for each type.
I will keep the current method for now, and will improve this at next Minecraft version update.
