### ISSUE TITLE
Processing Coal, Lapis Lazuli, Diamond, Redstone, Emerald, Nether Quartz is not working in 1.20.1. Recipes broken.

### ISSUE THREAD

**Issue by stardustdragon96** [gisellevonbingen/Minecraft-MoreMekanismProcessing#45]
please fix this, I beg you..

**Comment by gisellevonbingen** [comment]
Can't reproduce.
Please more detail.

![image](https://github.com/gisellevonbingen-Minecraft/MoreMekanismProcessing/assets/44163945/5b526892-45a7-4642-b2f8-2ffc38888b8a)


![image](https://github.com/gisellevonbingen-Minecraft/MoreMekanismProcessing/assets/44163945/d510c039-c694-4efc-8152-5c7ab11a213d)
