### ISSUE TITLE
Can't make Silver blocks (Ice and fire)

### ISSUE THREAD

**Issue by Thelegendking** [gisellevonbingen/Minecraft-MoreMekanismProcessing#47]
The Silver ingots from this mod can't be converted into Silver blocks and same goes for silver nuggets can't be made into silver ingot(of I&F's), if you could just add a crafting recipe with silver ingot from this mod and convert it into Ice and fire's silver ingot that might solve the whole issue.

**Comment by gisellevonbingen** [comment]
Ice and fire's recipes are not support 'tags'.
They only accept exact items.

It need change from Ice and fire mod.

`silver_ingot_to_silver_block.json`
```json
{
  "type": "minecraft:crafting_shaped",
  "category": "building",
  "key": {
    "#": {
      "item": "iceandfire:silver_ingot"
    }
  },
  "pattern": [
    "###",
    "###",
    "###"
  ],
  "result": {
    "item": "iceandfire:silver_block"
  },
  "show_notification": true
}
```
