### ISSUE TITLE
[Integration Suggestion] Add Titanium processing items

### ISSUE THREAD

**Issue by JuicyCosmos** [gisellevonbingen/Minecraft-MoreMekanismProcessing#9]
Titanium is not in a lot of modpacks but some of the mods I use do have this kind of ore, like Better Diving. This is just a simple suggestion since titanium doesn't get used a lot but I feel bad when there's this single ore that doesn't have mekanism compat.

**Comment by gisellevonbingen** [comment]
```I feel bad when there's this single ore that doesn't have mekanism compat.```
I feel bad too, I want to make all ores compatible if possible

Titanium integration work will begin soon
Please wait

**Comment by gisellevonbingen** [comment]
https://github.com/gisellevonbingen/Minecraft-MoreMekanismProcessing/issues/12#issuecomment-898469728

**Comment by gisellevonbingen** [comment]
https://github.com/gisellevonbingen/Minecraft-MoreMekanismProcessing/issues/13#issuecomment-898544607

Integration  'LibVulpes (Advanced Rocketry)' completed

Can libvulpes:orerutile blocks can processing to titanium ingots
